import React, { useState, useEffect } from 'react'
import { Loader, Card, FormField } from '../components'

const RenderCards = ({data , title}) => {
    // Check if data prop is an array with a length greater than 0
    if (data?.length > 0 ) {
      // Map over the data array and return a new array of Card components
      return data.map((post) => <Card key={post._id} {...post} />)
    }
    // If the data prop is not an array or if the array is empty, return the title prop
    return <h2 className="mt-5 font-bold text-[#3650a8] text-xl uppercase">{title}</h2>
  }
  

const Home = () => {

    const [loading, setLoading] = useState(false);
    const [allPost, setAllPost] = useState(null);

    const [searchText, setSearchTest] = useState('');

    return (
        <section className="max-w-7xl mx-auto">
            <div>
                <h1 className="font-extrabold text-[#222328] text-[32px]"> The Community Showcase</h1>
                <p className="mt-2 text-[#606e77] text-[16px] max-w[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
            </div>

            <div className="mt-16">
                <FormField />
            </div>

            <div className="mt-10">
                {loading ? (
                    <div className="flex justify-center items-center">
                        <Loader />
                    </div>) : (
                    <>
                    {searchText && (
                        <h2 className="font-medium text-[#606e76] text-xl mb-3">
                            Showing results for  <span className="text-[#222328]"> {searchText}</span>
                             </h2>
                    )}

                    <div className="gird lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                        {searchText ?(
                            <RenderCards 
                            data={[]}
                            title="No results found" />
                        ) : (
                            <RenderCards
                            data={[]}
                            title="No posts found" />
                        )}
                    </div>
                    </>
                )
                }
            </div>

        </section>
    )
}

export default Home